# Set zsh as default shell for all new windows
set-option -g default-shell /usr/bin/bash

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

## Enable mouse support
set -g mouse on

## Fix colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

## Session name max characters
set -g status-left-length 30


# Binds

# Create new window in current session with prefix-c
bind c new-window

# Split window vertically/horizontally with prefix-[backslash|hyphen]
bind | split-window -h
bind - split-window -v

# Switch panes with prefix-[u|i]
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Switch windows with prefix-[u|i]
bind -n M-u previous-window
bind -n M-i next-window

# Switch sessions with prefix-[y|o]
bind -n M-y switch-client -p
bind -n M-o switch-client -n


# Remove annoying keybinds
unbind '"'
unbind %

# Reload .tmux.conf with prefix-r
bind r source-file $HOME/.tmux.conf

# tmux plugin manager (keep at bottom)

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
