scan_timeout = 100

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ░▒▓█](c1)\
$os\
$username\
[](bg:c2 fg:c1)\
$directory\
[](bg:c3 fg:c2)\
$git_branch\
$git_status\
[](bg:c4 fg:c3)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bg:c5 fg:c4)\
$conda\
[](bg:c6 fg:c5)\
$time\
$cmd_duration\
[█▓▒░ ](fg:c6)\
$line_break\
$character"""

palette = 'xby'

[os]
disabled = false
style = "bg:c1 fg:white"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:c1 fg:white"
style_root = "bg:c1 fg:white"
format = '[ $user ]($style)'

[directory]
style = "bg:c2 fg:white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:c3 fg:white"
format = '[[ $symbol $branch ](fg:white bg:c3)]($style)'

[git_status]
style = "bg:c3 fg:white"
format = '[[($all_status$ahead_behind )](fg:white bg:c3)]($style)'

[nodejs]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[bun]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[c]
symbol = " "
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[rust]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[golang]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[php]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[java]
symbol = " "
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[kotlin]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[haskell]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version) ](fg:white bg:c4)]($style)'

[python]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:white bg:c4)]($style)'

[docker_context]
symbol = ""
style = "bg:c4 fg:white"
format = '[[ $symbol( $context) ](fg:white bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "bg:c5 fg:white"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:c6 fg:white"
format = '[[  $time ](fg:white bg:c6)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[λ](bold fg:gold)'
error_symbol = '[λ](bold fg:gold)'
vimcmd_symbol = '[λ](bold fg:gold)'
vimcmd_replace_one_symbol = '[λ](bold fg:gold)'
vimcmd_replace_symbol = '[λ](bold fg:gold)'
vimcmd_visual_symbol = '[λ](bold fg:gold)'

[cmd_duration]
show_milliseconds = true
format = '[[ in $duration](fg:white bg:c6)]($style)'
style = "bg:c6 fg:white"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.xby]
c1 = "#111E2C"
c2 = "#203040"
c3 = "#2e4155"
c4 = "#3d5369"
c5 = "#4c657d"
c6 = "#5b7791"
c7 = "#6988a6"
c8 = "#789aba"
gold = "#da9c62"
white = "#ffffff"
black = "#000000"
